config/routes.rb
WhereIsBen::Application.routes.draw do
  root to: 'application#map'
  resources :events

  post '/sms' => 'twilio#sms'

  resources :admin, only: [:index] do
    collection do
      get 'google_authorization_callback'
      get 'oauth2authorize'
    end
  end

end

app/models/address.rb
class Address
  extend ActiveModel::Naming
  include ActiveModel::Conversion  ## takes care of initialize for us
  attr_accessor :street, :city, :state, :zipcode, :creator_id

  def initialize(options={})

    @street = options[:street]
    @city = options[:city]
    @state = options[:state]
    @zipcode = options[:zipcode]
    @creator_id = options[:creator_id]
  end

  def persisted?; false; end

  def as_venue
    address = Geocoder.search("#{address}, #{city}, #{state} #{zipcode}")
    return nil if address.blank?

    latitude = address.first.latitude
    longitude = address.first.longitude
    Venue.new name: name, latitude: latitude, longitude: longitude, creator_id: creator_id
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password_confirmation
  authenticates_with_sorcery!
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :ensure_session
  before_filter do
    # Ensure user has authorized the app
    unless user_credentials.access_token || request.path_info =~ /auth/
      redirect_to oauth2authorize_admin_index_path
    end
  end

  after_filter do
    # Serialize the access/refresh token to the session
    session[:access_token] = user_credentials.access_token
    session[:refresh_token] = user_credentials.refresh_token
    session[:expires_in] = user_credentials.expires_in
    session[:issued_at] = user_credentials.issued_at
  end

  def index
    if session[:retrieving_events]
      redirect_to(events_path)
    else
      session[:retrieving_events] = true
      Event.destroy_all('id is not null')
      # Fetch list of events on the user's default calandar
      EventImporter.import_events!(user_credentials)
      session[:retrieving_events] = nil
      redirect_to events_path
    end
  end

  def google_authorization_callback
    # Exchange token
    user_credentials.code = params[:code] if params[:code]
    user_credentials.fetch_access_token!
    redirect_to admin_index_path
  end

  def oauth2authorize
    response.status = 303
    redirect_to user_credentials.authorization_uri.to_s
  end

  private
  def ensure_session
    session[:activated] = true
  end

  def user_credentials
    # Build a per-request oauth credential based on token stored in session
    # which allows us to use a shared API client.
    @authorization ||= $client.authorization.dup.tap do |auth|
      auth.redirect_uri = google_authorization_callback_admin_index_url
      auth.update_token!(session.instance_variable_get('@delegate'))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def map
    render template: 'shared/map'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    start_time = (params[:start_time] ? Date.parse(params[:start_time]) : Date.today).beginning_of_week
    @events = Event.where('start_time >= ? and end_time <= ?', start_time, start_time + 7)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:external_id, :client, :start_time, :end_time, :sequence, :latitude, :longitude, :recurs)
    end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
  def sms
    @client = Twilio::REST::Client.new TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN
    @client.account.sms.messages.create(
      :from => '+14242887652',
      :to => '+13109232319',
      :body => (params[:message], params[:number], params[:sender])
    )
    redirect to root_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :external_id %><br>
    <%= f.text_field :external_id %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :sequence %><br>
    <%= f.number_field :sequence %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :recurs %><br>
    <%= f.check_box :recurs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<div class="table-responsive">
  <table class='table table-hover'>
    <colgroup>
      <col span='2' style='background-color: #fcf8e3' />
      <col span='2' style='background-color: #dff0d8' />
    </colgroup>
    <thead>
      <tr>
        <th>External</th>
        <th>Client</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Sequence</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Recurs</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= truncate event.external_id, length: 25 %></td>
          <td><%= event.client %></td>
          <td><%= event.start_time %></td>
          <td><%= event.end_time %></td>
          <td><%= event.sequence %></td>
          <td><%= event.latitude %></td>
          <td><%= event.longitude %></td>
          <td><%= event.recurs %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>External:</strong>
  <%= @event.external_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @event.client %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @event.sequence %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event.longitude %>
</p>

<p>
  <strong>Recurs:</strong>
  <%= @event.recurs %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAIY9iIAZvSyGDWT3v1X4aEDZRmIjGMClE&sensor=true">
  </script>
  <title>WhereIsBen</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class='container'>
<%= yield %>
</div>
</body>
</html>

app/views/shared/map.html.erb
<div id = "site-title">
  <p> Where's Ben? </p>
</div>

<div id ="container">
  <div class='row-fluid'>
    Show the week of <input id='date-picker' type="date" />
  </div>
</div>

<script type='text/javascript'>
$(document).ready(function() {
  baseEventsUrl = '<%= events_path format: 'json' %>';
  createLegend();
  initializeMapAndMarkers(baseEventsUrl);
});
</script>

<div class='row-fluid'>
  <div id="map"></div>
  <div id='map-legend'></div>
</div>

<p> Use Twilio to send text-messages directly to my phone!</p>
<%=form_tag("/sms",method: :post) do%>
  <input type="text" name="sender"  placeholder="Name">
  <input type="text" name="message" placeholder="Message">
  <input type="text" name="number"  placeholder="Phone">
  <button>Send</button>
<% end %>